---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - datadoghq.com
  resources:
  - datadogmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
