---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kuberik.com
  resources:
  - monitorchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kuberik.com
  resources:
  - monitorchecks/finalizers
  verbs:
  - update
- apiGroups:
  - kuberik.com
  resources:
  - monitorchecks/status
  verbs:
  - get
  - patch
  - update
